name: Preprocessing Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch: # bisa dijalankan manual dari tab Actions

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: preprocessing # semua "run" jalan dari folder preprocessing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib

      - name: Run preprocessing script
        run: |
          python automate_Nama-siswa.py

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-data
          # path relatif dari root repo, jadi tambahkan "preprocessing/"
          path: preprocessing/data_preprocessed/*.csv
